//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinaceTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class DU
    {
        public int DUID { get; set; }
        public int AMID { get; set; }
        public string DUName { get; set; }
        public int SDUID { get; set; }
        public int DUHeadID { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public string Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual User User { get; set; }
        public virtual SDU SDU { get; set; }
    }
}
