//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinaceTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUHTestTable
    {
        public long S_No { get; set; }
        public string CustomerName { get; set; }
        public string AMName { get; set; }
        public string LOBName { get; set; }
        public string DUName { get; set; }
        public string DBBLDU { get; set; }
        public Nullable<int> OpportunityID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string ProgramName { get; set; }
        public string ServiceLine { get; set; }
        public string ProductGroup { get; set; }
        public Nullable<decimal> sowvalue { get; set; }
        public Nullable<bool> poavailable { get; set; }
        public Nullable<decimal> pobalance { get; set; }
        public Nullable<int> AMJ19_FC { get; set; }
        public Nullable<int> AMJ19_Act { get; set; }
    }
}
