//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinaceTool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FinanceToolEntities : DbContext
    {
        public FinanceToolEntities()
            : base("name=FinanceToolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<DealStage> DealStages { get; set; }
        public virtual DbSet<DU> DUs { get; set; }
        public virtual DbSet<DUHTestTable> DUHTestTables { get; set; }
        public virtual DbSet<LOB> LOBs { get; set; }
        public virtual DbSet<Opportunity> Opportunities { get; set; }
        public virtual DbSet<OpportunityForecastBySale> OpportunityForecastBySales { get; set; }
        public virtual DbSet<OpportunityForecastBySales2> OpportunityForecastBySales2 { get; set; }
        public virtual DbSet<ProductGroup> ProductGroups { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectActualByDUH> ProjectActualByDUHs { get; set; }
        public virtual DbSet<ProjectForecastByDUH> ProjectForecastByDUHs { get; set; }
        public virtual DbSet<Quater> Quaters { get; set; }
        public virtual DbSet<Quater1> Quater1 { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SDU> SDUs { get; set; }
        public virtual DbSet<ServiceLine> ServiceLines { get; set; }
        public virtual DbSet<SOWStatu> SOWStatus { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserAccess> UserAccesses { get; set; }
        public virtual DbSet<Opportunity_Latest> Opportunity_Latest { get; set; }
        public virtual DbSet<quater_Actual> quater_Actual { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual ObjectResult<AMTable_Result> AMTable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AMTable_Result>("AMTable");
        }
    
        public virtual ObjectResult<Usp_GetAdminMainDetails_Result> Usp_GetAdminMainDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetAdminMainDetails_Result>("Usp_GetAdminMainDetails");
        }
    
        public virtual ObjectResult<Usp_GetAdminMainDetails_V1_Result> Usp_GetAdminMainDetails_V1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetAdminMainDetails_V1_Result>("Usp_GetAdminMainDetails_V1");
        }
    
        public virtual ObjectResult<Usp_GetAdminMainDetails_V2_Result> Usp_GetAdminMainDetails_V2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetAdminMainDetails_V2_Result>("Usp_GetAdminMainDetails_V2");
        }
    
        public virtual ObjectResult<Usp_GetAmDetailsbyProjectId_Result> Usp_GetAmDetailsbyProjectId(string projectId)
        {
            var projectIdParameter = projectId != null ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetAmDetailsbyProjectId_Result>("Usp_GetAmDetailsbyProjectId", projectIdParameter);
        }
    
        public virtual ObjectResult<Usp_GetAmMainDetails_Result> Usp_GetAmMainDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetAmMainDetails_Result>("Usp_GetAmMainDetails");
        }
    
        public virtual ObjectResult<Usp_GetAmMainDetails_Test_Result> Usp_GetAmMainDetails_Test()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetAmMainDetails_Test_Result>("Usp_GetAmMainDetails_Test");
        }
    
        public virtual ObjectResult<Usp_GetAmMainDetails_V1_Result> Usp_GetAmMainDetails_V1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetAmMainDetails_V1_Result>("Usp_GetAmMainDetails_V1");
        }
    
        public virtual ObjectResult<Usp_GetAmMainDetails_V2_Result> Usp_GetAmMainDetails_V2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetAmMainDetails_V2_Result>("Usp_GetAmMainDetails_V2");
        }
    
        public virtual ObjectResult<Usp_GetDUHDetails_Comparision_Result> Usp_GetDUHDetails_Comparision(string sDUID, string dUID)
        {
            var sDUIDParameter = sDUID != null ?
                new ObjectParameter("SDUID", sDUID) :
                new ObjectParameter("SDUID", typeof(string));
    
            var dUIDParameter = dUID != null ?
                new ObjectParameter("DUID", dUID) :
                new ObjectParameter("DUID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDUHDetails_Comparision_Result>("Usp_GetDUHDetails_Comparision", sDUIDParameter, dUIDParameter);
        }
    
        public virtual ObjectResult<Usp_GetDUHDetails_Comparision_OldDetails_Result> Usp_GetDUHDetails_Comparision_OldDetails(string sDUID, string dUID, Nullable<System.DateTime> date)
        {
            var sDUIDParameter = sDUID != null ?
                new ObjectParameter("SDUID", sDUID) :
                new ObjectParameter("SDUID", typeof(string));
    
            var dUIDParameter = dUID != null ?
                new ObjectParameter("DUID", dUID) :
                new ObjectParameter("DUID", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDUHDetails_Comparision_OldDetails_Result>("Usp_GetDUHDetails_Comparision_OldDetails", sDUIDParameter, dUIDParameter, dateParameter);
        }
    
        public virtual ObjectResult<Usp_GetDUHDetails_Comparision_V1_Result> Usp_GetDUHDetails_Comparision_V1(string sDUID, string dUID)
        {
            var sDUIDParameter = sDUID != null ?
                new ObjectParameter("SDUID", sDUID) :
                new ObjectParameter("SDUID", typeof(string));
    
            var dUIDParameter = dUID != null ?
                new ObjectParameter("DUID", dUID) :
                new ObjectParameter("DUID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDUHDetails_Comparision_V1_Result>("Usp_GetDUHDetails_Comparision_V1", sDUIDParameter, dUIDParameter);
        }
    
        public virtual ObjectResult<Usp_GetDUHDetails_Comparision_V2_Result> Usp_GetDUHDetails_Comparision_V2(string sDUID, string dUID)
        {
            var sDUIDParameter = sDUID != null ?
                new ObjectParameter("SDUID", sDUID) :
                new ObjectParameter("SDUID", typeof(string));
    
            var dUIDParameter = dUID != null ?
                new ObjectParameter("DUID", dUID) :
                new ObjectParameter("DUID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDUHDetails_Comparision_V2_Result>("Usp_GetDUHDetails_Comparision_V2", sDUIDParameter, dUIDParameter);
        }
    
        public virtual ObjectResult<Usp_GetDUHeadMainDetails_Result> Usp_GetDUHeadMainDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDUHeadMainDetails_Result>("Usp_GetDUHeadMainDetails");
        }
    
        public virtual ObjectResult<Usp_GetDUHMainDetails_Result> Usp_GetDUHMainDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDUHMainDetails_Result>("Usp_GetDUHMainDetails");
        }
    
        public virtual ObjectResult<Usp_GetDUHMainDetails_07_02_2019_Result> Usp_GetDUHMainDetails_07_02_2019()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDUHMainDetails_07_02_2019_Result>("Usp_GetDUHMainDetails_07_02_2019");
        }
    
        public virtual ObjectResult<Usp_GetDUHMainDetails_27_06_2019_Result> Usp_GetDUHMainDetails_27_06_2019()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDUHMainDetails_27_06_2019_Result>("Usp_GetDUHMainDetails_27_06_2019");
        }
    
        public virtual ObjectResult<Usp_GetDUHMainDetails_27_06_2019_backup_Result> Usp_GetDUHMainDetails_27_06_2019_backup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDUHMainDetails_27_06_2019_backup_Result>("Usp_GetDUHMainDetails_27_06_2019_backup");
        }
    
        public virtual ObjectResult<Usp_GetDUHMainDetails_V1_Result> Usp_GetDUHMainDetails_V1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDUHMainDetails_V1_Result>("Usp_GetDUHMainDetails_V1");
        }
    
        public virtual ObjectResult<Usp_GetDUHMainDetails_V2_Result> Usp_GetDUHMainDetails_V2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDUHMainDetails_V2_Result>("Usp_GetDUHMainDetails_V2");
        }
    
        public virtual ObjectResult<Usp_GetDUHMainDetailsByUserID_Result> Usp_GetDUHMainDetailsByUserID(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDUHMainDetailsByUserID_Result>("Usp_GetDUHMainDetailsByUserID", userIDParameter);
        }
    
        public virtual ObjectResult<Usp_GetDUHMainDetailsByUserID_V1_Result> Usp_GetDUHMainDetailsByUserID_V1(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDUHMainDetailsByUserID_V1_Result>("Usp_GetDUHMainDetailsByUserID_V1", userIDParameter);
        }
    
        public virtual ObjectResult<Usp_GetDUHMainDetailsByUserID_V2_Result> Usp_GetDUHMainDetailsByUserID_V2(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDUHMainDetailsByUserID_V2_Result>("Usp_GetDUHMainDetailsByUserID_V2", userIDParameter);
        }
    
        public virtual ObjectResult<Usp_GetDUMasterDetails_Result> Usp_GetDUMasterDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDUMasterDetails_Result>("Usp_GetDUMasterDetails");
        }
    
        public virtual ObjectResult<Usp_GetOpportunityDetails_Result> Usp_GetOpportunityDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetOpportunityDetails_Result>("Usp_GetOpportunityDetails");
        }
    
        public virtual ObjectResult<Usp_GetPMOOpportunityDetails_Result> Usp_GetPMOOpportunityDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetPMOOpportunityDetails_Result>("Usp_GetPMOOpportunityDetails");
        }
    
        public virtual ObjectResult<Usp_GetProjectMasterDetails_Result> Usp_GetProjectMasterDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetProjectMasterDetails_Result>("Usp_GetProjectMasterDetails");
        }
    
        public virtual ObjectResult<Usp_GetSDUMasterDetails_Result> Usp_GetSDUMasterDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetSDUMasterDetails_Result>("Usp_GetSDUMasterDetails");
        }
    
        public virtual ObjectResult<Usp_GetUserMasterDetails_Result> Usp_GetUserMasterDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetUserMasterDetails_Result>("Usp_GetUserMasterDetails");
        }
    
        public virtual int Usp_InsertOpportunityLatest(Nullable<int> opportunityID, string opportunityName, Nullable<int> dealStageID, Nullable<int> sowStatusID, Nullable<int> aMID, Nullable<int> customerID, string programName, Nullable<int> serviceLineID, Nullable<int> productGroupID, Nullable<int> dBBLDUID, Nullable<decimal> tCV, Nullable<decimal> acv, Nullable<int> sowvalue, Nullable<System.DateTime> billingStratDate, string note, string createdby, Nullable<System.DateTime> createddate, string modifiedby, Nullable<System.DateTime> modifiedDate, Nullable<int> salesForceCastID, Nullable<bool> isActive, Nullable<long> salesForceGuid, Nullable<int> dUID, Nullable<int> lobId, Nullable<decimal> sowStatusValue, Nullable<int> userid, Nullable<int> roleId, Nullable<bool> isMapped, Nullable<bool> isUpdated, string opportunitycategory)
        {
            var opportunityIDParameter = opportunityID.HasValue ?
                new ObjectParameter("OpportunityID", opportunityID) :
                new ObjectParameter("OpportunityID", typeof(int));
    
            var opportunityNameParameter = opportunityName != null ?
                new ObjectParameter("OpportunityName", opportunityName) :
                new ObjectParameter("OpportunityName", typeof(string));
    
            var dealStageIDParameter = dealStageID.HasValue ?
                new ObjectParameter("DealStageID", dealStageID) :
                new ObjectParameter("DealStageID", typeof(int));
    
            var sowStatusIDParameter = sowStatusID.HasValue ?
                new ObjectParameter("SowStatusID", sowStatusID) :
                new ObjectParameter("SowStatusID", typeof(int));
    
            var aMIDParameter = aMID.HasValue ?
                new ObjectParameter("AMID", aMID) :
                new ObjectParameter("AMID", typeof(int));
    
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            var programNameParameter = programName != null ?
                new ObjectParameter("ProgramName", programName) :
                new ObjectParameter("ProgramName", typeof(string));
    
            var serviceLineIDParameter = serviceLineID.HasValue ?
                new ObjectParameter("ServiceLineID", serviceLineID) :
                new ObjectParameter("ServiceLineID", typeof(int));
    
            var productGroupIDParameter = productGroupID.HasValue ?
                new ObjectParameter("ProductGroupID", productGroupID) :
                new ObjectParameter("ProductGroupID", typeof(int));
    
            var dBBLDUIDParameter = dBBLDUID.HasValue ?
                new ObjectParameter("DBBLDUID", dBBLDUID) :
                new ObjectParameter("DBBLDUID", typeof(int));
    
            var tCVParameter = tCV.HasValue ?
                new ObjectParameter("TCV", tCV) :
                new ObjectParameter("TCV", typeof(decimal));
    
            var acvParameter = acv.HasValue ?
                new ObjectParameter("acv", acv) :
                new ObjectParameter("acv", typeof(decimal));
    
            var sowvalueParameter = sowvalue.HasValue ?
                new ObjectParameter("sowvalue", sowvalue) :
                new ObjectParameter("sowvalue", typeof(int));
    
            var billingStratDateParameter = billingStratDate.HasValue ?
                new ObjectParameter("BillingStratDate", billingStratDate) :
                new ObjectParameter("BillingStratDate", typeof(System.DateTime));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            var createdbyParameter = createdby != null ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(string));
    
            var createddateParameter = createddate.HasValue ?
                new ObjectParameter("Createddate", createddate) :
                new ObjectParameter("Createddate", typeof(System.DateTime));
    
            var modifiedbyParameter = modifiedby != null ?
                new ObjectParameter("Modifiedby", modifiedby) :
                new ObjectParameter("Modifiedby", typeof(string));
    
            var modifiedDateParameter = modifiedDate.HasValue ?
                new ObjectParameter("ModifiedDate", modifiedDate) :
                new ObjectParameter("ModifiedDate", typeof(System.DateTime));
    
            var salesForceCastIDParameter = salesForceCastID.HasValue ?
                new ObjectParameter("SalesForceCastID", salesForceCastID) :
                new ObjectParameter("SalesForceCastID", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var salesForceGuidParameter = salesForceGuid.HasValue ?
                new ObjectParameter("SalesForceGuid", salesForceGuid) :
                new ObjectParameter("SalesForceGuid", typeof(long));
    
            var dUIDParameter = dUID.HasValue ?
                new ObjectParameter("DUID", dUID) :
                new ObjectParameter("DUID", typeof(int));
    
            var lobIdParameter = lobId.HasValue ?
                new ObjectParameter("LobId", lobId) :
                new ObjectParameter("LobId", typeof(int));
    
            var sowStatusValueParameter = sowStatusValue.HasValue ?
                new ObjectParameter("SowStatusValue", sowStatusValue) :
                new ObjectParameter("SowStatusValue", typeof(decimal));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(int));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var isMappedParameter = isMapped.HasValue ?
                new ObjectParameter("IsMapped", isMapped) :
                new ObjectParameter("IsMapped", typeof(bool));
    
            var isUpdatedParameter = isUpdated.HasValue ?
                new ObjectParameter("IsUpdated", isUpdated) :
                new ObjectParameter("IsUpdated", typeof(bool));
    
            var opportunitycategoryParameter = opportunitycategory != null ?
                new ObjectParameter("opportunitycategory", opportunitycategory) :
                new ObjectParameter("opportunitycategory", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_InsertOpportunityLatest", opportunityIDParameter, opportunityNameParameter, dealStageIDParameter, sowStatusIDParameter, aMIDParameter, customerIDParameter, programNameParameter, serviceLineIDParameter, productGroupIDParameter, dBBLDUIDParameter, tCVParameter, acvParameter, sowvalueParameter, billingStratDateParameter, noteParameter, createdbyParameter, createddateParameter, modifiedbyParameter, modifiedDateParameter, salesForceCastIDParameter, isActiveParameter, salesForceGuidParameter, dUIDParameter, lobIdParameter, sowStatusValueParameter, useridParameter, roleIdParameter, isMappedParameter, isUpdatedParameter, opportunitycategoryParameter);
        }
    
        public virtual int Usp_Update_Opportunity_IsMapped(Nullable<int> opportunityID)
        {
            var opportunityIDParameter = opportunityID.HasValue ?
                new ObjectParameter("OpportunityID", opportunityID) :
                new ObjectParameter("OpportunityID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_Update_Opportunity_IsMapped", opportunityIDParameter);
        }
    
        public virtual int Usp_UpdateIsActiveQuaters(string currentQuater, string firstQuater, string secondQuater, string thiredQuater)
        {
            var currentQuaterParameter = currentQuater != null ?
                new ObjectParameter("CurrentQuater", currentQuater) :
                new ObjectParameter("CurrentQuater", typeof(string));
    
            var firstQuaterParameter = firstQuater != null ?
                new ObjectParameter("FirstQuater", firstQuater) :
                new ObjectParameter("FirstQuater", typeof(string));
    
            var secondQuaterParameter = secondQuater != null ?
                new ObjectParameter("SecondQuater", secondQuater) :
                new ObjectParameter("SecondQuater", typeof(string));
    
            var thiredQuaterParameter = thiredQuater != null ?
                new ObjectParameter("ThiredQuater", thiredQuater) :
                new ObjectParameter("ThiredQuater", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_UpdateIsActiveQuaters", currentQuaterParameter, firstQuaterParameter, secondQuaterParameter, thiredQuaterParameter);
        }
    
        public virtual int Usp_UpdateOpportunity(Nullable<int> opportunityID)
        {
            var opportunityIDParameter = opportunityID.HasValue ?
                new ObjectParameter("OpportunityID", opportunityID) :
                new ObjectParameter("OpportunityID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_UpdateOpportunity", opportunityIDParameter);
        }
    
        public virtual int Usp_UpdateOpportunityLatest(Nullable<int> opportunityID)
        {
            var opportunityIDParameter = opportunityID.HasValue ?
                new ObjectParameter("OpportunityID", opportunityID) :
                new ObjectParameter("OpportunityID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_UpdateOpportunityLatest", opportunityIDParameter);
        }
    
        public virtual ObjectResult<Usp_GetForecastValues_Result> Usp_GetForecastValues()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetForecastValues_Result>("Usp_GetForecastValues");
        }
    }
}
