//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinaceTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public int OpportunityID { get; set; }
        public int SowStatusID { get; set; }
        public string poavilable { get; set; }
        public string Note { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public string Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string pobalance { get; set; }
        public string ProjectCode { get; set; }
    
        public virtual Opportunity Opportunity { get; set; }
        public virtual SOWStatu SOWStatu { get; set; }
    }
}
