//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinaceTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quater
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quater()
        {
            this.OpportunityForecastBySales = new HashSet<OpportunityForecastBySale>();
            this.ProjectActualByDUHs = new HashSet<ProjectActualByDUH>();
            this.ProjectForecastByDUHs = new HashSet<ProjectForecastByDUH>();
        }
    
        public int QuaterID { get; set; }
        public System.DateTime StratDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string QuaterName { get; set; }
        public string description { get; set; }
        public Nullable<int> QuaterNumber { get; set; }
        public Nullable<int> year { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public string Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpportunityForecastBySale> OpportunityForecastBySales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectActualByDUH> ProjectActualByDUHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectForecastByDUH> ProjectForecastByDUHs { get; set; }
    }
}
