//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinaceTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class quater_Actual
    {
        public int QuaterID { get; set; }
        public System.DateTime StratDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string QuaterName { get; set; }
        public string description { get; set; }
        public Nullable<int> QuaterNumber { get; set; }
        public Nullable<int> year { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public string Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
